---
version: 0.2

phases:
   pre_build:
      commands:
         - $(aws ecr get-login --no-include-email)
   build:
      commands:
         - test ${PACKER_VERSION+x}
         - curl -sS -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
         - unzip -q packer.zip
         - docker build -t ami-build-env:latest .
         - docker tag ami-build-env "${REPOSITORY}"
         - docker push "${REPOSITORY}"
