---
version: 0.2

phases:
   pre_build:
      commands:
         - $(aws ecr get-login --no-include-email)
   build:
      commands:
         - test ${PACKER_VERSION+x}
         - if test ! -f "packer_${PACKER_VERSION}_linux_amd64.zip" ; then curl -sS -O "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" ; fi
         - unzip -q packer_*.zip
         - docker build -t ami-build-env:latest .
         - docker tag ami-build-env "${REPOSITORY}"
         - docker push "${REPOSITORY}"

cache:
   paths:
      - packer_*.zip
