---
version: 0.2

env:
   variables:
      TAG: 'latest'

phases:
   install:
      commands:
         - DEBIAN_FRONTEND=noninteractive apt-get -qq install jq
   build:
      commands:
         - if test -z ${PACKER_VERSION+x} ; then PACKER_VERSION="$(curl -sS 'https://checkpoint-api.hashicorp.com/v1/check/packer' | jq -r '.current_version')" ; fi
         - if test -f "packer_${PACKER_VERSION}_amd64" ; then ln -s -- "packer_${PACKER_VERSION}_amd64" packer ; else curl -sS -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip" ; unzip -q packer.zip ; ln -s -- packer "packer_${PACKER_VERSION}_amd64" ; fi
         - if test ! -f 'get-pip.py' ; then curl -sS -O 'https://bootstrap.pypa.io/get-pip.py' ; fi
         - docker build -t "ami-build-env:${TAG}" .
         - docker tag "ami-build-env:${TAG}" "${REPOSITORY}:${TAG}"
         - $(aws ecr get-login --no-include-email)
         - docker push "${REPOSITORY}:${TAG}"

cache:
   paths:
      - get-pip.py
      - packer_*_amd64
