---
version: 0.2

env:
   variables:
      TAG: 'latest'

phases:
   install:
      commands:
         - if test -z ${PACKER_VERSION+x} ; then DEBIAN_FRONTEND=noninteractive apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install jq ; fi
   build:
      commands:
         - if test -z ${PACKER_VERSION+x} ; then PACKER_VERSION="$(curl -sS 'https://checkpoint-api.hashicorp.com/v1/check/packer' | jq -r '.current_version')" ; fi
         - |
            if test -f "packer_${PACKER_VERSION}_linux_amd64"
            then
               ln -s -- "packer_${PACKER_VERSION}_linux_amd64" packer
            else
               curl -sS -o packer-checksums.txt "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS"
               curl -sS -O "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
               # The coreutils package in the build container is too old and sha256sum doesn't support --ignore-missing, so irrelevant entries in the checksums file must be filtered out
               sed -e '/\s*packer_.*_linux_amd64\.zip$/!d' packer-checksums.txt | sha256sum -c --strict
               unzip -q "packer_${PACKER_VERSION}_linux_amd64.zip"
               ln -s -- packer "packer_${PACKER_VERSION}_linux_amd64"
            fi
         - docker build -t "ami-build-env:${TAG}" .
         - docker tag "ami-build-env:${TAG}" "${REPOSITORY}:${TAG}"
         - $(aws ecr get-login --no-include-email)
         - docker push "${REPOSITORY}:${TAG}"

cache:
   paths:
      - packer_*_linux_amd64
